### ISSUE TITLE
API not performing updates of the rates since 2018-09-06

### ISSUE THREAD

**Issue by ghost** [openratesapi/openrates#1]
It looks like api not performing updates of the rates since "date": "2018-09-06" .Need to check the service or perform the restart of the API.

**Comment by labeh** [comment]
I have the same issue while requesting the API. Seems like data gets not updated.

**Comment by julian-zehetmayr** [comment]
This issue has now been fixed and rates are updating again. We' sorry for the delay here.

**Comment by ghost** [comment]
Thank you for fast reply. Issue solved. API working properly.
